// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Api_Client_Generator
{
    internal sealed partial class Vsix
    {
        public const string Id = "Api_Client_Generator.b9d4a27b-aced-4191-8135-cfc98df42adc";
        public const string Name = "API Client Generator";
        public const string Description = @"Generates a API client class, all you need to provide is the swagger.json file of the endpoints. Uses NSwag Package under the hood.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ahmed Youssef";
        public const string Tags = "";
    }
}
