// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGeneratorPackageString = "9000ca6d-9294-4c30-85dc-ffd20b56af39";
        public static Guid guidGeneratorPackage = new Guid(guidGeneratorPackageString);

        public const string guidGeneratorPackageCmdSetString = "b6ce2924-a6ec-496c-81e6-5074198f242d";
        public static Guid guidGeneratorPackageCmdSet = new Guid(guidGeneratorPackageCmdSetString);

        public const string guidImagesString = "2a342b4a-8c74-4e92-9473-1a83e7181af7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}